/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    UApp: typeof import('./node_modules/.pnpm/@nuxt+ui@3.0.0_@babel+parser@7.26.10_axios@1.8.3_embla-carousel@8.5.2_qrcode@1.5.4_type_ed485faaf8562a2b38cbe7d8ff6822cf/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UButton: typeof import('./node_modules/.pnpm/@nuxt+ui@3.0.0_@babel+parser@7.26.10_axios@1.8.3_embla-carousel@8.5.2_qrcode@1.5.4_type_ed485faaf8562a2b38cbe7d8ff6822cf/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCard: typeof import('./node_modules/.pnpm/@nuxt+ui@3.0.0_@babel+parser@7.26.10_axios@1.8.3_embla-carousel@8.5.2_qrcode@1.5.4_type_ed485faaf8562a2b38cbe7d8ff6822cf/node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
    UInput: typeof import('./node_modules/.pnpm/@nuxt+ui@3.0.0_@babel+parser@7.26.10_axios@1.8.3_embla-carousel@8.5.2_qrcode@1.5.4_type_ed485faaf8562a2b38cbe7d8ff6822cf/node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    ULinkBase: typeof import('./node_modules/.pnpm/@nuxt+ui@3.0.0_@babel+parser@7.26.10_axios@1.8.3_embla-carousel@8.5.2_qrcode@1.5.4_type_ed485faaf8562a2b38cbe7d8ff6822cf/node_modules/@nuxt/ui/dist/runtime/components/LinkBase.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
